### ISSUE TITLE
Contact me please

### ISSUE THREAD

**Issue by jonnitg** [imackme/misthos#3]
Hi @imackme,

I wanted to know if you will using this repo in the future, 
'cause I want to do a new repo with the same name as you have this repo "misthos" (new project incoming),
and ask you if I can have that name. Please contact me. 

I will appreciate very much your answer :)

Thanks, jonnitg
**galtrev@gmail.com**

**Comment by imackme** [comment]
Hi @jonnitg 

Sorry for the late reply. This is a future project and I am eyeing on this name as well.
Let me know if you still want it.

Regards,
@imackme

**Comment by jonnitg** [comment]
No problem, already have new name :) srry for bother you...

Thanks anyway
@jonnitg
